nguage: ruby
rvm:
- 2.3.0
before_script:
- chmod +x ./script/cibuild
script: 
- bundle exec rake deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- openssl aes-256-cbc -K $encrypted_5722a4a44b23_key -iv $encrypted_5722a4a44b23_iv
  -in .deploy_key.enc -out .deploy_key -d
- chmod 600 .deploy_key
